from . import auth_router
from . import user_router
from . import role_router
from . import inventario_excluido_router
from . import dias_entrega_proveedor_router
from . import vista_inventarios_router
from . import sugerido_compras_router
from . import grupos_router
from . import proveedores_router
from . import permiso_router